name: Deploy Static Site
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Files
        uses: actions/upload-pages-artifact@v2
        with:
          path: './'
      - name: Deploy
        uses: actions/deploy-pages@v2
